config/routes.rb
Rails.application.routes.draw do
    resources :members
    resources  :branches

    root to: "members#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
	validates_presence_of :number
	validates_presence_of :name

	def self.search(search)
 		if search
 		  where('name LIKE ?', "%#{search}%")
 		else
 		  all.order('number ASC')
 		end
	end

	before_validation do |model|
  	model.number.reject!(&:blank?) if model.number
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.search(params[:search])
  end

  def show
    find_member
  end

  def new
    @member = Member.new
  end

  def edit
    find_member
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      redirect_to members_path(@member)
    else 
      render 'new'
    end
  end

  def update
    find_member
    if @member.update(member_params)
      redirect_to member_path(@member)
    else
      render 'edit'
    end
  end

  def destroy
    find_member
    @member.destroy
  end 

  private
    def find_member
      @member = Member.find(params[:id])
    end

    def member_params
      params.require(:member).permit(:name, :number, :spouse, :checkbox_value, :birthdate, :deathdate, :note, :search)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KwanTree</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_for [@member] do |f| %>
    
      <% if @member.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@member.errors.count, "error") %> prohibited
            this input from being saved:
          </h2>
          <ul>
            <% @member.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <p>
        <%= f.label "Name" %><br>
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.label "Number" %><br>
        <%= f.text_field :number, placeholder: "separate each branch with a comma - ex. 7,2,3,1,2" %>
      </p>
      <p>
        <%= f.label "Spouse?" %><br>
        <%= f.check_box :spouse %>
      </p>
      <p>
        <%= f.label "Birth Year" %><br>
        <%= f.number_field :birthdate %>
      </p>
      <p>
        <%= f.label "Death Year" %><br>
        <%= f.number_field :deathdate %>
      </p>
      <p>
        <%= f.label "Note (optional)" %><br> 
        <%= f.text_area :note, placeholder: "contact info, location, remarriages, etc." %>
      </p>

      <p>
        <%= f.submit "Add/Update Post" %>
      </p>

<% end %>

app/views/members/edit.html.erb
<%= render 'form' %>

app/views/members/index.html.erb
<%= form_tag(members_path, method: :get) do %>
  <%= text_field_tag :search, params[:search], placeholder: 'Name Search - case sensitive', class: 'searchFormField' %>
  <%= submit_tag 'Search', name: nil %>
<% end %>


<p>Add a <%= link_to 'new family member', new_member_path %></p>


<h1>Kwan Family</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	<% @members.each do |member| %>
    	<tr>
      	<td><%= member.name %></td>
      	<td><% member.number.each do |num| %>
						<%= num %>
					<% end %>
					<% if member.spouse == true %>
						S
					<% end %></td>
      	<td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
     </tr>   
     <% end %>    
  </tbody>
</table>

app/views/members/new.html.erb
<%= render 'form' %>

app/views/members/show.html.erb
<%= @member.name %><br>

Family Number:
<% @member.number.each do |num| %>
	<%= num %>
	<% if @member.spouse == true %>
		S
	<% end %>
<% end %><br>

<% if @member.birthdate != nil %>
	Birth: <%= @member.birthdate %><br>
<% end %> 
<% if @member.deathdate != nil %>
	Death: <%= @member.deathdate %><br>
<% end %>

<% if @member.note %>
	Notes: <%= @member.note %>
<% end %>
<br><br><br>


<%= link_to 'Edit', edit_member_path %> - 
<%= link_to 'Delete', member_path, method: :delete, data: { confirm: "Are you sure? -- really really really really truly positively absolutely sure!??" } %>